### ISSUE TITLE
[Indexer API] Self hosted indexer api

### ISSUE THREAD

**Issue by DaraDoyoung** [aptos-labs/aptos-indexer-processors#201]
## Description
Is there any updates on self hosted indexer api?
https://aptos.dev/indexer/api/self-hosted

I'm running processors which are saving data to Postgres DB, and I would like to open an endpoint to this.
It seems no guide on this is provided yet.

**Comment by larry-aptos** [comment]
you can use hasura self-hosted solution(hasura docker image) and https://github.com/aptos-labs/aptos-indexer-processors/tree/main/hasura-api/metadata-json this file as the metadata to use.

**Comment by olivbau** [comment]
How to import the `unified.json` file?
At : `/console/settings/metadata-actions` ?


![telegram-cloud-photo-size-4-5812408267522031740-y](https://github.com/aptos-labs/aptos-indexer-processors/assets/11538800/4c6b0623-7453-4cd5-850f-58bcb35cceeb)

I have an error:

![image](https://github.com/aptos-labs/aptos-indexer-processors/assets/11538800/45f5b6de-d616-412a-a10a-55ffada9af0c)
```
[
    {
        "definition": "indexer-v2",
        "name": "source indexer-v2",
        "reason": "Inconsistent object: environment variable 'INDEXER_V2_POSTGRES_URL' not set",
        "type": "source"
    },
    {
        "definition": {
            "name": "Latest Processor Status",
            "query": "query LatestProcessorStatus {\n  processor_status {\n    processor\n    last_updated\n    last_success_version\n    last_transaction_timestamp\n  }\n}"
        },
        "name": "query_collections Latest Processor Status in allowed-queries",
        "reason": "Inconsistent object: In query collection \"allowed-queries\" the query \"Latest Processor Status\" is invalid with the following error(s): \"$.processor_status: field 'processor_status' not found in object 'query_root'\". This query is being used in the following REST endpoint(s): \"Latest Processor Status\". This query is in allowlist.",
        "type": "query_collections"
    }
]
```

**Comment by olivbau** [comment]
I'm trying to import the `unified.json` file to Hasura.
For people struggling, don't forget to add `INDEXER_V2_POSTGRES_URL` env var to your docker compose file

Something like this:
```
  graphqlengine:
    image: hasura/graphql-engine:latest
    ports:
      - 8080:8080
    restart: always
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres_user:postgres_password@dbhasura:5432/hasura
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      HASURA_GRAPHQL_DEV_MODE: "false"
      INDEXER_V2_POSTGRES_URL: postgres://postgres_user:postgres_password@localhost:5432/indexer
```
