### ISSUE TITLE
[Custom Processors]  Coin Flip

### ISSUE THREAD

**Issue by dconroy** [aptos-labs/aptos-indexer-processors#244]
## Description

Using docker compose and the coin_flip index processor, i believe i am streaming events and detecting coin flip events, but nothing is getting written to the postgres database. I have verified connection strings, database and table names and am able to connect through a SQL tool, but the tables are always empty.

Does this log output mean that it should be writing an event?

`index-processor-1  | {"timestamp": "2024-01-19 22:08:10,486", "level": "INFO", "fields": {"message": "[Parser] DB insertion time of one batch of transactions", "processor_name": "coin_flip", "start_version": "628091000", "end_version": "628091999", "service_type": "processor", "num_of_transactions": "1000", "duration_in_secs": "0.00018042", "size_in_bytes": "2939880"}, "module": "worker", "func_name": "run", "path_name": "/app/utils/worker.py", "line_no": 538}
`
## Repro

config.yaml

connecting to testnet

 # Optional. Start processor at starting_version
    starting_version: 626589722
    # Optional. Stop processor after ending_version.
    ending_version: 646589730

docker-compose.yaml
```

version: '3'
services:
  index-processor:
    build: .
    environment:
      DB_CONNECTION_URI: postgresql://coin_flip:postgres@db:5432/coin_flip
    depends_on:
      - db
    volumes:
      - ./config.yaml:/app/config/config.yaml
  db:
    image: postgres:15.2
    environment:
      POSTGRES_USER: coin_flip
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:

```
