### ISSUE TITLE
[Indexer API] graphql API server

### ISSUE THREAD

**Issue by DogLi** [aptos-labs/aptos-indexer-processors#343]
How to build the graphql API server in Python or in Rust?

**Comment by banool** [comment]
I assume you're asking how to run the indexer API, which serves requests for the DB populated but the core indexer processors.

If so, this is not something you build. Instead, we use Hasura. You need to run Hasura and apply the Hasura metadata we publish.

I'll update this answer soon with how to do that.

**Comment by DogLi** [comment]
Yes, we followed the Hasura doc, it works. Thanks.

**Comment by mshakeg** [comment]
In case anyone's interested in knowing how to setup Hasura. I'm running `postgres` in docker and so I have `hasura` start up after `postgres`. Now to have hasura track tables that you want to be able to query navigate to the `http://localhost:8080/console/data/default/schema/public` page and select the db then table then click "Track"


```
version: '3.6'
services:
  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
    ports:
      - "${DB_PORT}:5432"

  graphql-engine:
    image: hasura/graphql-engine:latest
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgresql://${DB_USERNAME}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log

volumes:
  db_data:
```
